#FROM ubuntu:trusty
FROM debian:12

MAINTAINER Henri Casanova <henric@hawaii.edu>

RUN apt-get update

# install languages
RUN apt-get -y install g++

# build environment
RUN apt-get -y install wget
RUN apt-get -y install cmake

# experimental environment
RUN apt-get install -y time

# install boost
RUN apt-get -y install libboost-all-dev

# install vim
RUN apt-get -y install vim

# install doxygen
RUN apt-get -y install doxygen 

# install SimGrid
RUN wget --no-check-certificate https://framagit.org/simgrid/simgrid/-/archive/v3_15/simgrid-v3_15.tar.gz && tar -xf simgrid-v3_15.tar.gz
RUN cd simgrid-v3_15 && head -157 ./src/kernel/context/Context.hpp > /tmp/Context.hpp && echo "#undef SIGSTKSZ" >> /tmp/Context.hpp && echo "#define SIGSTKSZ 20480" >> /tmp/Context.hpp && tail -33 ./src/kernel/context/Context.hpp >> /tmp/Context.hpp && /bin/mv /tmp/Context.hpp ./src/kernel/context/Context.hpp 

RUN cd simgrid-v3_15 && mkdir build && cd build && cmake .. && make -j12  && make install && cd ../.. && /bin/rm -rf simgrid-*

# Add user
RUN apt-get install -y sudo
RUN useradd -ms /bin/bash simgrid
RUN adduser simgrid sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER simgrid
WORKDIR /home/simgrid
