#FROM ubuntu:trusty
FROM debian:12

MAINTAINER Henri Casanova <henric@hawaii.edu>

RUN apt-get update

# install languages
RUN apt-get -y install g++

# build environment
RUN apt-get -y install wget
RUN apt-get -y install cmake

# experimental environment
RUN apt-get install -y time

# install boost
RUN apt-get -y install libboost-all-dev

# install doxygen
RUN apt-get -y install doxygen 

# install editor
RUN apt-get -y install vim


# install SimGrid
RUN wget --no-check-certificate https://framagit.org/simgrid/simgrid/-/archive/v3_10/simgrid-v3_10.tar.gz && tar -xf simgrid-v3_10.tar.gz && cd simgrid-v3_10 && head -92 ./CMakeLists.txt > /tmp/CMakeLists.txt &&  tail -151 ./CMakeLists.txt >> /tmp/CMakeLists.txt && mv /tmp/CMakeLists.txt ./CMakeLists.txt && mkdir build && cd build && cmake .. && make -j12  && make install

# install GooglePerf
RUN apt-get install -y google-perftools
# Create a convenient soft link to the profiler.so file
RUN ln -s /usr/lib/aarch64-linux-gnu/libprofiler.so.0 /usr/local/lib/libprofiler.so


# Add user
RUN apt-get install -y sudo
RUN useradd -ms /bin/bash simgrid
RUN adduser simgrid sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER simgrid
WORKDIR /home/simgrid
