#FROM ubuntu:jammy
FROM debian:12

MAINTAINER Henri Casanova <henric@hawaii.edu>

RUN apt-get update

# install languages
RUN apt-get -y install g++

# build environment
RUN apt-get -y install wget
RUN apt-get -y install cmake
RUN apt-get -y install sudo

# experimental environment
RUN apt-get install -y time

# install boost
RUN apt-get -y install libboost-all-dev

# install doxygen
RUN apt-get -y install doxygen 

# install vim
RUN apt-get -y install vim

# install git
RUN apt-get -y install git

# install SimGrid
RUN git clone https://framagit.org/simgrid/simgrid.git && cd simgrid && git checkout 718bee0ecd82d03ef877e66f9ecb77c9e69a599b
RUN cd simgrid && mkdir build && cd build && cmake -Denable_SMPI=off .. && make -j8 && sudo make install

# install GooglePerf
#RUN apt-get install -y google-perftools
# Create a convenient soft link to the profiler.so file
#RUN ln -s /usr/lib/aarch64-linux-gnu/libprofiler.so.0 /usr/local/lib/libprofiler.so


# Add user
RUN apt-get install -y sudo
RUN useradd -ms /bin/bash simgrid
RUN adduser simgrid sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER simgrid
WORKDIR /home/simgrid
