#FROM ubuntu:jammy
FROM debian:12

MAINTAINER Henri Casanova <henric@hawaii.edu>

RUN apt-get update

# install languages
RUN apt-get -y install g++

# build environment
RUN apt-get -y install wget
RUN apt-get -y install cmake
RUN apt-get -y install sudo

# experimental environment
RUN apt-get install -y time

# install boost
RUN apt-get -y install libboost-all-dev

# install doxygen
RUN apt-get -y install doxygen 

# install vim
RUN apt-get -y install vim

# install git
RUN apt-get -y install git

# install SimGrid
#RUN git clone https://framagit.org/simgrid/simgrid.git
#RUN cd simgrid && git checkout 9db79d70d969bdb58f26c689ad4f965b3d9e80cf 
#RUN sed -i "s/list<CommImplPtr>/deque<CommImplPtr>/" simgrid/src/kernel/activity/MailboxImpl.hpp
#RUN cd simgrid &&  mkdir build && cd build && cmake -Denable_smpi=off .. && make -j8 && sudo make install
RUN wget --no-check-certificate https://framagit.org/simgrid/simgrid/-/archive/v3.36/simgrid-v3.36.tar.gz && tar -xf simgrid-v3.36.tar.gz && cd simgrid-v3.36 && cmake . && make && sudo make install && cd .. && rm -rf simgrid-v3.36*



# Add user
RUN apt-get install -y sudo
RUN useradd -ms /bin/bash simgrid
RUN adduser simgrid sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER simgrid
WORKDIR /home/simgrid
