FROM ubuntu:trusty

MAINTAINER Henri Casanova <henric@hawaii.edu>

RUN apt-get update

# install languages
RUN apt-get -y install g++

# build environment
RUN apt-get -y install wget
RUN apt-get -y install cmake

# experimental environment
RUN apt-get install -y time

# install boost
RUN apt-get -y install libboost-all-dev

# install doxygen
RUN apt-get -y install doxygen 

# install SimGrid
RUN wget --no-check-certificate https://framagit.org/simgrid/simgrid/-/archive/v3_14/simgrid-v3_14.tar.gz && tar -xf simgrid-v3_14.tar.gz && cd simgrid-v3_14 && mkdir build && cd build && cmake .. && make && sudo make install && cd ../.. && /bin/rm -rf simgrid-*

# Add user
RUN useradd -ms /bin/bash simgrid
RUN adduser simgrid sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER simgrid
WORKDIR /home/simgrid
